Repository softlayer/githubio_source, pull requests merged in 2020-01, with the labels that each got.

#300 properly blocked off the SOAP / XMLRPC examples
  content/article/authenticating-softlayer-api.md
Labels: Documentation

#301 Fix softlayer/softlayer.github.io#157
  content/python/order_block_file_storage_with_managers.md
Labels: Documentation

#299 refactored the DNS python articles into a single article.
  content/python/createDNS.md
  content/python/create_Dns_Zone.py.md
  content/python/delete_domain_resource_record.py.md
  content/python/dns_management.md
  content/python/edit_record.py.md
  content/python/forward_zone_details.py.md
  content/python/get_records.py.md
  content/python/get_reverse_domain_records.py.md
  content/python/list_zones.py.md
Labels: Documentation

#306 20200110 release notes
  content/release_notes/2019/20191216.md
  content/release_notes/2020/20200110.md
Labels: Release

#307 Transient guests article
  config.toml
  content/article/TransientGuests.md
  content/article/how-solve-error-fetching-http-headers.md
  content/article/object-masks.md
  content/article/using-result-limits-softlayer-api.md
  content/article/xml-rpc.md
  content/blog/phil/how-solve-error-fetching-http-headers.md
  content/release_notes/2020/20200117.md
  layouts/_default/single.html
  layouts/article/single.html
  static/css/custom.css
Labels: Documentation, enhancement

#308 20200117 Release
  content/reference/services/SoftLayer_Search/advancedSearch.md
  content/reference/services/SoftLayer_Search/getObjectTypes.md
  content/reference/services/SoftLayer_Search/search.md
Labels: Release

#309 20200121 Release
  content/reference/datatypes/SoftLayer_Container_Network_CdnMarketplace_Configuration_Performance_DynamicContentAcceleration/_index.md
  content/reference/datatypes/SoftLayer_Network_Storage/_index.md
  content/reference/datatypes/SoftLayer_Network_Storage_Backup/_index.md
  content/reference/datatypes/SoftLayer_Network_Storage_Backup_Evault/_index.md
  content/reference/datatypes/SoftLayer_Network_Storage_Backup_Evault_Version6/_index.md
  content/reference/datatypes/SoftLayer_Network_Storage_Hub/_index.md
  content/reference/datatypes/SoftLayer_Network_Storage_Hub_Swift/_index.md
  content/reference/datatypes/SoftLayer_Network_Storage_Hub_Swift_Container/_index.md
  content/reference/datatypes/SoftLayer_Network_Storage_Hub_Swift_Version1/_index.md
  content/reference/datatypes/SoftLayer_Network_Storage_Iscsi/_index.md
  content/reference/datatypes/SoftLayer_Network_Storage_Iscsi_EqualLogic_Version3/_index.md
  content/reference/datatypes/SoftLayer_Network_Storage_Iscsi_EqualLogic_Version3_Replicant/_index.md
  content/reference/datatypes/SoftLayer_Network_Storage_Iscsi_EqualLogic_Version3_Snapshot/_index.md
  content/reference/datatypes/SoftLayer_Network_Storage_Nas/_index.md
  content/reference/datatypes/SoftLayer_Network_Storage_OpenStack_Object/_index.md
  content/reference/datatypes/SoftLayer_Network_Storage_Replicant/_index.md
  content/reference/datatypes/SoftLayer_Network_Storage_Snapshot/_index.md
  content/reference/services/SoftLayer_Network_Storage/_index.md
  content/reference/services/SoftLayer_Network_Storage/convertCloneDependentToIndependent.md
  content/reference/services/SoftLayer_Network_Storage/getDependentDuplicates.md
  content/reference/services/SoftLayer_Network_Storage_Backup_Evault/_index.md
  content/reference/services/SoftLayer_Network_Storage_Backup_Evault/convertCloneDependentToIndependent.md
  content/reference/services/SoftLayer_Network_Storage_Backup_Evault/getDependentDuplicates.md
  content/reference/services/SoftLayer_Network_Storage_Iscsi/_index.md
  content/reference/services/SoftLayer_Network_Storage_Iscsi/convertCloneDependentToIndependent.md
  content/reference/services/SoftLayer_Network_Storage_Iscsi/getDependentDuplicates.md
Labels: Release

#311 Metric tracking object python examples
  content/python/metric_tracking_object.py.md
Labels: Documentation

#312 20200130 Release
  content/reference/datatypes/McAfee_Epolicy_Orchestrator_Version51_Agent_Details/_index.md
  content/reference/datatypes/McAfee_Epolicy_Orchestrator_Version51_Policy_Object/_index.md
  content/reference/datatypes/McAfee_Epolicy_Orchestrator_Version51_Product_Properties/_index.md
  content/reference/datatypes/SoftLayer_Account/_index.md
  content/reference/datatypes/SoftLayer_Container_Network_Storage_DataCenterLimits_VolumeCountLimitContainer/_index.md
  content/reference/datatypes/SoftLayer_Container_User_Customer_Profile_Event_HyperWarp_ProfileChange_EventProperties/_index.md
  content/reference/datatypes/SoftLayer_Software_Component_AntivirusSpyware_Mcafee_Epo_Version51/_index.md
  content/reference/datatypes/SoftLayer_Software_Component_HostIps_Mcafee_Epo_Version51/_index.md
  content/reference/datatypes/list.html
  content/reference/services/SoftLayer_Account/_index.md
  content/reference/services/SoftLayer_Account/getNetworkCreationFlag.md
  content/reference/services/SoftLayer_Network_Storage/_index.md
  content/reference/services/SoftLayer_Network_Storage/getVolumeCountLimits.md
  content/reference/services/SoftLayer_Network_Storage_Backup_Evault/_index.md
  content/reference/services/SoftLayer_Network_Storage_Backup_Evault/getVolumeCountLimits.md
  content/reference/services/SoftLayer_Network_Storage_Iscsi/_index.md
  content/reference/services/SoftLayer_Network_Storage_Iscsi/getVolumeCountLimits.md
Labels: Release
