Repository softlayer/githubio_source, pull requests merged in 2021-05, with the labels that each got.

#479 Add Event logs example in Goland
  content/go/event_log.go.md
Labels: Documentation, Example

#481 Fix infinite loop in goland event logs example.
  content/go/event_log.go.md
Labels: Example, bug

#476 Hardware components and versions, python script example
  content/python/hardware_components.py.md
Labels: Documentation

#483 20210525 Release
  content/reference/datatypes/SoftLayer_User_Customer/_index.md
  content/reference/datatypes/SoftLayer_User_Customer_OpenIdConnect/_index.md
  content/reference/services/SoftLayer_User_Customer/_index.md
  content/reference/services/SoftLayer_User_Customer/getHasFullVirtualGuestAccessFlag.md
  content/reference/services/SoftLayer_User_Customer_OpenIdConnect/_index.md
  content/reference/services/SoftLayer_User_Customer_OpenIdConnect/getHasFullVirtualGuestAccessFlag.md
Labels: Release
