Repository softlayer/githubio_source, pull requests merged in 2024-06, with the labels that each got.

#663 20240605 release notes
  content/reference/datatypes/SoftLayer_Location.md
  content/reference/datatypes/SoftLayer_Network_Backbone.md
  content/reference/datatypes/SoftLayer_Network_Backbone_Location_Dependent.md
  content/reference/datatypes/SoftLayer_User_Permission_Department.md
  content/reference/services/SoftLayer_Hardware_Component_Model/getVmwareQualifiedFirmwares.md
  content/reference/services/SoftLayer_Hardware_SecurityModule/changeRedfishPowerState.md
  content/reference/services/SoftLayer_Hardware_SecurityModule/getRedfishPowerState.md
  content/reference/services/SoftLayer_Hardware_SecurityModule750/changeRedfishPowerState.md
  content/reference/services/SoftLayer_Hardware_SecurityModule750/getRedfishPowerState.md
  content/reference/services/SoftLayer_Hardware_Server/changeRedfishPowerState.md
  content/reference/services/SoftLayer_Hardware_Server/getRedfishPowerState.md
  content/reference/services/SoftLayer_Location/_index.md
  content/reference/services/SoftLayer_Location/getBackboneDependents.md
  content/reference/services/SoftLayer_Location_Datacenter/getBackboneDependents.md
  content/reference/services/SoftLayer_Network_Backbone/_index.md
  content/reference/services/SoftLayer_Network_Backbone/getAllBackbones.md
  content/reference/services/SoftLayer_Network_Backbone/getBackbonesForLocationName.md
  content/reference/services/SoftLayer_Network_Backbone/getHealth.md
  content/reference/services/SoftLayer_Network_Backbone/getLocation.md
  content/reference/services/SoftLayer_Network_Backbone/getNetworkComponent.md
  content/reference/services/SoftLayer_Network_Backbone/getObject.md
  content/reference/services/SoftLayer_Network_Backbone_Location_Dependent/_index.md
  content/reference/services/SoftLayer_Network_Backbone_Location_Dependent/getAllObjects.md
  content/reference/services/SoftLayer_Network_Backbone_Location_Dependent/getDependentLocation.md
  content/reference/services/SoftLayer_Network_Backbone_Location_Dependent/getObject.md
  content/reference/services/SoftLayer_Network_Backbone_Location_Dependent/getSourceDependentsByName.md
  content/reference/services/SoftLayer_Network_Backbone_Location_Dependent/getSourceLocation.md
  content/reference/services/SoftLayer_User_Permission_Action/getDepartment.md
  content/reference/services/SoftLayer_User_Permission_Department/_index.md
  content/reference/services/SoftLayer_User_Permission_Department/getAllObjects.md
  content/reference/services/SoftLayer_User_Permission_Department/getObject.md
  content/reference/services/SoftLayer_User_Permission_Department/getPermissions.md
  content/release_notes/2024/20240605.md
Labels: Release

#665 Update object-filters.md
  content/article/object-filters.md
Labels: bug

#667 Update SuscribeUserUnplainedIncident.rb.md
  content/ruby/SuscribeUserUnplainedIncident.rb.md
Labels: enhancement

#668 added a link to directly edit the articles
  layouts/partials/feedback-menu.html
Labels: enhancement

#669 Update object-filters.md
  content/article/object-filters.md
Labels: bug

#673 Dark theme!
  layouts/article/section.html
  layouts/article/single.html
  layouts/article/summary.html
  layouts/index.html
  layouts/partials/feedback-menu.html
  layouts/partials/footer.copyright.html
  layouts/partials/header.html
  layouts/partials/header.includes.html
  layouts/partials/navbar.html
  layouts/partials/title.html
  layouts/reference/datatype.html
  layouts/reference/method.html
  layouts/reference/service.html
  layouts/reference/single.html
  static/css/bootstrap.css
  static/css/custom.css
  static/css/dark.css
  static/css/light.css
  static/css/main.css
Labels: enhancement

#675 Some minor style issues related to dark theme
  config.toml
  content/release_notes/2024/20240619.md
  layouts/partials/navbar.html
  static/css/custom.css
  static/css/light.css
Labels: enhancement

#676 Minor style change
  layouts/article/section.html
Labels: enhancement
